version: 2

builds:
  - main: ./cmd/hun
    binary: hun
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}

archives:
  - formats:
      - tar.gz
    name_template: "hun_{{ .Os }}_{{ .Arch }}"

homebrew_casks:
  - repository:
      owner: hundotsh
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    name: hun
    binaries:
      - hun
    homepage: "https://hun.sh"
    description: "Seamless project context switching for developers"
    url:
      verified: "github.com/sourabhrathourr/hun/"
    commit_author:
      name: hun-bot
      email: bots@hun.sh
    commit_msg_template: "Brew cask update for {{ .ProjectName }} {{ .Tag }}"

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
